name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.0'

      - name: Install dependencies
        run: |
          go version
          sudo apt install golint -y
          go mod download

      - name: Run build
        run: |
          cd cmd/
          go build .

      # Run vet & lint on the code
      - name: Run vet & lint
        run: |
          cd cmd/
          go vet .
          golint .

      # Run testing on the code
      - name: Run testing
        run: cd ./uniq && go test -v
