name: CI

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - 'master'

jobs:
  build_hw1_part1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.0'

      - name: Install dependencies
        run: go get ./...
      - name: Run build
        run: |
          cd hw1_part1/cmd/
          go build .
  tests_hw1_part1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.0'


      # Run testing on the code
      - name: Run testing
        run: |
          go get ./...
          cd hw1_part1/
          go test -v ./...

  build_hw1_part2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.0'

      - name: Install dependencies
        run: go get ./...
      - name: Run build
        run: |
          cd hw1_part2/cmd/
          go build .
  tests_hw1_part2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.0'


      # Run testing on the code
      - name: Run testing
        run: |
          go get ./...
          cd hw1_part2/
          go test -v ./...
