name: CI

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.0'

      - name: Install dependencies
        run: |
          go version
          sudo apt install golint -y
          go get ./...
      - name: Run build
        run: |
          cd cmd/
          go build .
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.0'


      # Run testing on the code
      - name: Run testing
        run: go test -v ./...
